# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: lincolnbrito.projects::lang.form.name.team

# Model Form Field configuration
form: $/lincolnbrito/projects/models/team/fields.yaml

# Model Class name
modelClass: LincolnBrito\Projects\Models\Team

# Default redirect location
defaultRedirect: lincolnbrito/projects/teams

# Create page
create:
    title: lincolnbrito.projects::lang.form.create.form_title.teams
    redirect: lincolnbrito/projects/teams/update/:id
    redirectClose: lincolnbrito/projects/teams

# Update page
update:
    title: lincolnbrito.projects::lang.form.update.form_title.teams
    redirect: lincolnbrito/projects/teams
    redirectClose: lincolnbrito/projects/teams

# Preview page
preview:
    title: lincolnbrito.projects::lang.form.preview.form_title.teams
